package br.com.his.assistencial.model;

public enum AtendimentoEventoTipo {
    ATENDIMENTO_CRIADO,
    TRIAGEM_FINALIZADA,
    EPISODIO_ABERTO,
    ENTRADA_REGISTRADA,
    FINALIZADO,
    TRANSFERENCIA_SOLICITADA,
    TRANSFERENCIA_SAIDA,
    TRANSFERENCIA_RECEBIDA,
    TRANSFERENCIA_CANCELADA
}
