CREATE TABLE unidade_federativa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    sigla CHAR(2) NOT NULL,
    codigo_ibge CHAR(2),
    CONSTRAINT uq_unidade_federativa_sigla UNIQUE (sigla)
);

CREATE TABLE cidade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    unidade_federativa_id BIGINT NOT NULL REFERENCES unidade_federativa(id),
    codigo_ibge CHAR(5),
    CONSTRAINT uq_cidade_nome_uf UNIQUE (nome, unidade_federativa_id)
);

ALTER TABLE paciente
    ADD COLUMN cidade_id BIGINT;

ALTER TABLE paciente
    ADD CONSTRAINT fk_paciente_cidade
    FOREIGN KEY (cidade_id) REFERENCES cidade(id);

CREATE INDEX idx_cidade_unidade_federativa ON cidade(unidade_federativa_id);
CREATE INDEX idx_cidade_nome ON cidade(nome);
CREATE INDEX idx_paciente_cidade ON paciente(cidade_id);
